name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: |
          ./gradlew build -Dmysql.username=${{ secrets.MYSQL_USERNAME }} \
                          -Dmysql.password=${{ secrets.MYSQL_PASSWORD }} \
                          -Dmysql.url=${{ secrets.MYSQL_URL }} \
                          -Djwt.secret.key=${{ secrets.JWT_SECRET_KEY }} \
                          -Dgpt.api.key=${{ secrets.GPT_API_KEY }}

      - name: Build Docker image
        run: docker build -t kyoona/house-inception:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push kyoona/house-inception:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to EC2 and pull Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull kyoona/house-inception:latest
            docker stop spring-app || true
            docker rm spring-app || true
            docker run -d --name spring-app -p 8080:8080 \
              -e MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }} \
              -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
              -e MYSQL_URL=${{ secrets.MYSQL_URL }} \
              -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
              -e GPT_API_KEY=${{ secrets.GPT_API_KEY }} \
              kyoona/house-inception:latest

